import { mkdir, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import path from "node:path";
import { promisify } from "node:util";

const contracts = [
  { name: "AGCToken", constName: "agcTokenAbi" },
  { name: "AGCHook", constName: "agcHookAbi" },
  { name: "PolicyController", constName: "policyControllerAbi" },
  { name: "PolicyEngine", constName: "policyEngineAbi" },
  { name: "SettlementRouter", constName: "settlementRouterAbi" },
  { name: "StabilityVault", constName: "stabilityVaultAbi" },
  { name: "XAGCVault", constName: "xagcVaultAbi" },
];

const execFileAsync = promisify(execFile);

async function readAbi(root, contract) {
  const args = ["inspect", contract, "abi", "--json"];
  if (contract === "PolicyController") {
    args.push("--via-ir");
  }

  const { stdout } = await execFileAsync("forge", args, { cwd: root, maxBuffer: 16 * 1024 * 1024 });
  return JSON.parse(stdout);
}

async function main() {
  const root = process.cwd();
  const generatedDir = path.join(root, "web", "src", "generated");
  const outputPath = path.join(generatedDir, "abis.ts");

  await mkdir(generatedDir, { recursive: true });

  const lines = [
    "// Auto-generated by `pnpm generate:abis`.",
    "// Generated from `forge inspect` output.",
    "",
  ];

  for (const contract of contracts) {
    const abi = await readAbi(root, contract.name);
    lines.push(`export const ${contract.constName} = ${JSON.stringify(abi, null, 2)} as const;`);
    lines.push("");
  }

  lines.push("export const protocolAbis = {");
  for (const contract of contracts) {
    lines.push(`  ${contract.name}: ${contract.constName},`);
  }
  lines.push("} as const;");
  lines.push("");

  await writeFile(outputPath, `${lines.join("\n")}\n`, "utf8");
  console.log(`Wrote ${outputPath}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
